//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.20 at 10:38:36 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://uns.ac.rs/xml/team18")
package com.example.wsdl.consumewsdl.generate;
